import { build } from 'esbuild';
import { mkdir, cp, rm, readdir, readFile, writeFile } from 'node:fs/promises';
import { deploymentMetadata } from './metadata.mjs';
await mkdir('dist', { recursive: true });
const staticFiles = ['impressum.html','privacy.html','manifest.webmanifest','icons','models','ort','vendor','licenses','face-decoder.js','face-worker.js','sw.js','LICENSE','favicon.svg','favicon.ico','og-image.png'];
for (const file of staticFiles) await cp(file, `dist/${file}`, { recursive: true });
await build({ entryPoints: ['src/app.js','src/speech-worker.js'], bundle: true, format: 'esm', target: ['es2022'], outdir: 'dist', minify: true, legalComments: 'eof' });
for (const name of ['style.css','design-tokens.css','components.css']) await cp(`src/${name}`,`dist/${name}`);
await cp('node_modules/mediabunny/LICENSE','dist/licenses/MEDIABUNNY-LICENSE');
const siteConfig=JSON.parse(await readFile('site.config.json','utf8'));
const siteUrl=process.env.SITE_URL ?? siteConfig.url;
const metadata = deploymentMetadata(siteUrl);
await writeFile('dist/index.html',(await readFile('index.html','utf8')).replace('<!-- deployment-metadata -->',metadata.head));
await writeFile('dist/robots.txt',metadata.robots);
if (metadata.sitemap) await writeFile('dist/sitemap.xml',metadata.sitemap);
else await rm('dist/sitemap.xml',{force:true});
const expected = new Set([...staticFiles,'index.html','app.js','speech-worker.js','style.css','design-tokens.css','components.css','robots.txt',...(metadata.sitemap?['sitemap.xml']:[])]);
for (const name of await readdir('dist')) if (!expected.has(name)) await rm(`dist/${name}`, {recursive:true,force:true});
console.log(`Built Deface${siteUrl?' with public metadata':' (set SITE_URL for public SEO metadata)'}.`);
